### PR TITLE
Reworking and simplifying the Python side of MC++ memory management.

### PR DESCRIPTION
**Pull request by jsiirola**
## Summary/Motivation:
This PR moves the `__del__` of the root MC object from the visitor to the McCormick object.  It also converts the MC++ library interface to use a singleton pattern (so we don't have to keep setting it up or passing around a pointer to it).

## Changes proposed in this PR:
- Move the final `__del__` method to `McCormick.__del__`
- Convert library interface to use a singleton pattern.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by qtothec** [comment]
I was actually thinking about using a context manager idiom for handling this issue. What do you think of that?

**Comment by jsiirola** [comment]
The idea would be that you would only use McCormick objects as context managers?  Something like

```python
with McCormick(model.con1.body) as mc:
    # do somethign with cuts, etc
```

Is it likely that users will want to have multiple McCormick objects concurrently?  I could imagine that causing problems with the context manager approach.

**Comment by qtothec** [comment]
Wouldn't concurrency also cause issues with the singleton pattern with respect to error messages?

**Comment by jsiirola** [comment]
Yes, but that is a separate issue (neither approach is thread safe).  I don't think that Python loads the library multiple times with the current implementation (the SO is only linked in once), so I think you can already get into trouble with error messages.  That would be interesting to test, though.

I was less concerned with the concurrency aspect and more with users having to write:
```python
with McCormick(m.con1.body) as mc1:
    with McCormick(m.con2.body) as mc2:
        # ...
```
or the ability to support:
```python
mc_envelopes = [McCormick(c.body) for c in m.component_data_objects(Constraint)]
```

**Comment by jsiirola** [comment]
@qtothec: I tested the concurrency "problem", and as I suspected, it is identical between the current pyomo PR and the changes in this PR: Python only links a single instance of the `.so`, so the globals are shared across the McCormick objects in both implementations.  To confirm, I added the following to the original PR branch:
```cpp
// mcppInterface.cpp
extern "C" {
   const char * get_last_display() {
      return lastDisplay.c_str();
   }
   void set_last_display(const char * msg) {
      lastDisplay = msg;
   }
}
```
and
```python
# test_concurrent.py
import ctypes
from pyomo.environ import *
from pyomo.contrib.mcpp.pyomo_mcpp import McCormick

m = ConcreteModel()
m.x = Var(bounds=(-10,10))
m.y = Var(bounds=(-10,10))
a = McCormick(m.x*m.y)
b = McCormick(m.x+m.y)
print("IS:", a.mcpp_lib is b.mcpp_lib)
print(a.mcpp_lib)
print(b.mcpp_lib)
a.mcpp_lib.set_last_display.argtypes = [ctypes.c_char_p]
b.mcpp_lib.get_last_display.argtypes = []
b.mcpp_lib.get_last_display.restype = ctypes.c_char_p
a.mcpp_lib.set_last_display("hello")
print(b.mcpp_lib.get_last_display())
```
then
```
% python test_concurrent.py
IS: False
<CDLL '[...]/.pyomo/lib/mcppInterface.so', handle 1a8ef80 at 7fa436e29ad0>
<CDLL '[...]/.pyomo/lib/mcppInterface.so', handle 1a8ef80 at 7fa436e29dd0>
hello
```
In the end, for all GIL-based Python interpreters (including CPython and pypy), the GIL will "save us" and we should be fine.

**Comment by qtothec** [comment]
Wow, that's cool with the concurrency treating. I appear to have fallen asleep rather than respond promptly. I was dwelling on the fact that at some point, something is going to have to release all of the references, and whether it is a good idea to trust the user to do so.

I was thinking that we have something like:
```
with mcpp_context as mc:
    mc_envelopes = [mc(c.body) for c in m.component_data_objects(Constraint)]
    # do stuff with mc_envelopes
```

Since our MC objects end up needing to be regenerated for changes to the variable values, it's not worth it at this point to keep them around between multiple cut generation iterations, for example.

**Comment by jsiirola** [comment]
At this point, I think it is a "six of one, half dozen of the other" case.  The C++ programmer in me likes putting the cleanup in the container destructor (in this case, the McCormick objects), because that way we don't have to worry about all the ways the user may want to use the McCormick object (it will just always work).  But, I suspect that the context manager would be fine too.  The one extra case the context manager would need to handle (and throw a clean exception for) is:
```python
with mcpp_context() as mc:
    self.envelopes = [mc(c.body) for c in m.component_data_objects(Constraint)]
# ...
tmp = self.envelopes[i].subcc()
```

**Comment by qtothec** [comment]
Yeah, I had initially thought the same way, and that's why I stuck a `__del__` in to the walker. I'm having misgivings about that approach due to seeing things like this: https://stackoverflow.com/questions/1481488/what-is-the-del-method-how-to-call-it

Of course, there's conflicting advice out there with respect to using `__del__`, so if you think that it should work well enough, I'll go ahead and merge this, since I do agree with the principles of the changes.

**Pull request merged**
