### PR TITLE
initial bounds in fbbt

### PR DESCRIPTION
**Pull request by michaelbynum**
## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by michaelbynum** [comment]
@qtothec Let me know what you think of these changes. By the way, thanks for finding my bug when update_bonds is False. This should fix that. I had trouble running the tests in contrib/gdp_bounds. If you like these changes, would you mind quickly making sure I didn't break those tests?

**Comment by qtothec** [comment]
I'll try this out. It looks like I have an import loop because gdp_bounds is a plugin. I'm going to try to resolve that right now

**Comment by qtothec** [comment]
I resolved the import loop in gdp_bounds, but this set of changes to use var_bnds doesn't seem to work.

**Comment by michaelbynum** [comment]
This is odd. The tests pass on Travis in your PR. I didn't think I changed any imports...

**Comment by qtothec** [comment]
No, that's because I fixed the import loop on my branch. It wasn't your fault.

**Comment by michaelbynum** [comment]
@qtothec What do you think of a bounds manager like this? This would also allow me to get rid of the "update_variable_bounds" option. I want to avoid adding more and more options to the fbbt functions and walkers.

**Comment by michaelbynum** [comment]
@qtothec I guess I could also keep the keyword arguments to the fbbt functions and use the bounds manager within the fbbt functions. That would keep the fbbt functions/walkers simple. Thoughts/opinions?

**Comment by qtothec** [comment]
I think that seems to be a quite reasonable option.

**Pull request merged**
